name: Deploy-Site

on:  
  schedule:
    - cron: '0 1 * * 1,3'  # every monday and wednesday at 01:00 https://crontab.guru/#0_1_*_*_1,3

jobs:
  build:
    name: Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/606414ccc4193fb1ce3c8fad


